[package]
name = "builtin-embedded-binary-validation-utility"
version = "0.1.0"
edition = "2021"
[[bin]]
name = "builtin-embeddedBinaryValidationUtility"
path = "src/main.rs"

[dependencies]
xcbuild-builtin = { path = "../../crates/xcbuild-builtin" }
