[package]
name = "builtin-product-packaging-utility"
version = "0.1.0"
edition = "2021"
[[bin]]
name = "builtin-productPackagingUtility"
path = "src/main.rs"

[dependencies]
xcbuild-builtin = { path = "../../crates/xcbuild-builtin" }
