[package]
name = "builtin-info-plist-utility"
version = "0.1.0"
edition = "2021"
[[bin]]
name = "builtin-infoPlistUtility"
path = "src/main.rs"

[dependencies]
xcbuild-builtin = { path = "../../crates/xcbuild-builtin" }
