[package]
name = "builtin-copy-tiff"
version = "0.1.0"
edition = "2021"
[[bin]]
name = "builtin-copyTiff"
path = "src/main.rs"

[dependencies]
xcbuild-builtin = { path = "../../crates/xcbuild-builtin" }
